### ISSUE TITLE
CmdParser

### ISSUE THREAD

**Issue by mvaucher** [EPFL-SV-cpp-projects/Team_4#3]
Implémenter commandes pour récupérer les valeurs de T, l'intervalle de temps dT et le fichier de valeurs des gènes entrés par l'utilisateur. (.h et .cpp)

**Comment by Nchennoufi** [comment]
Si vous voulez que l'erreur ne soit pas fatale, il faut mettre des cerr
Pour le e.what, mettre des strings dans les throws

**Comment by Nchennoufi** [comment]
Il faudrait gérer le nombre initial de protéines et de RNA,
