### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by acurrat** [EPFL-SV-cpp-projects/Team_4#5]
classe Random pour temps de prochaine réaction + type prochaine réaction 
distributions exponentielle et uniforme

**Comment by acurrat** [comment]
même genre de classe que Random.h de NeuronNet pour exo noté 
2 fonctions pour chaque distribution : une void et une double (juste pour être sûrs)

**Comment by Nchennoufi** [comment]
Tu pourrais commenter pour doxygen ton header ! Sinon ça me semble ok, à voir une fois que le CMakeLists est fait ce que ça donne,
Bon courage !
